// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avxqihwxtyfucbjvxkqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2eHFpaHd4dHlmdWNianZ4a3FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDIyNjUsImV4cCI6MjA3MDIxODI2NX0._t2CLFc_N9twuT5akd9FzXUpXpFnHo-EKEKC5hYKrPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});